### ISSUE TITLE
ImportError: No module named 'jose' building 2.1.0 

### ISSUE THREAD

**Issue by pssuils** [python-social-auth/social-app-django#178]
Hi,

We've just run into this issue when building our images this morning. 
```
 Traceback (most recent call last):
  File "/root/project/embed_service/design/tests/test_admin.py", line 93, in setUp
    self.client.force_login(self.user)
  File "/usr/local/lib/python3.5/dist-packages/django/test/client.py", line 609, in force_login
    backend = get_backend()
  File "/usr/local/lib/python3.5/dist-packages/django/test/client.py", line 605, in get_backend
    backend = load_backend(backend_path)
  File "/usr/local/lib/python3.5/dist-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/usr/local/lib/python3.5/dist-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/dist-packages/unauth/backends.py", line 3, in <module>
    from social_core.backends.google_openidconnect import GoogleOpenIdConnect
  File "/usr/local/lib/python3.5/dist-packages/social_core/backends/google_openidconnect.py", line 5, in <module>
    from .open_id_connect import OpenIdConnectAuth
  File "/usr/local/lib/python3.5/dist-packages/social_core/backends/open_id_connect.py", line 5, in <module>
    from jose import jwk, jwt
ImportError: No module named 'jose'
```

We have a wrapper for `social-auth-app-django` and we currently use the version `2.1.0`. 

For that version [the requeriments](https://github.com/python-social-auth/social-app-django/blob/2.1.0/requirements.txt) allow to install `social-auth-core==2.0.0` which in [this commit](https://github.com/python-social-auth/social-core/commit/1e6dbf91ed6d798737a237e399c51f1655270440) is changing to introduce `python-jose`.

Probably constraining the use of `social-auth-core` for older versions of `social-auth-app-django` may resolve it.

**Comment by omab** [comment]
`python-jose` is part of `openid connect` integration, the requirement is defined in [requirements-openidconnect.txt](https://github.com/python-social-auth/social-core/blob/master/requirements-openidconnect.txt) and to install it you need to set the `openidconnect` extra require.

To mitigate this, add this dependency to your `requirements.txt` file: `social-auth-core[openidconnect]` or don't import openidconnect modules.
