### ISSUE TITLE
ImportError: cannot import name 'request'

### ISSUE THREAD

**Issue by marcosfreccia** [python-social-auth/social-app-django#179]
I am running on Python 3.6 and the latest version of django=2.1.3, and social-auth-app-django=3.1.0. When I try to run the migrate command, I get the following.

```pytb
(env) C:\Users\MyUser001\Documents\Private\GitHub\MyApp>python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\MyUser001\Documents\Private\GitHub\MyApp\env\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\MyUser001\Documents\Private\GitHub\MyApp\env\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    django.setup()
  File "C:\Users\MyUser001\Documents\Private\GitHub\MyApp\env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\MyUser001\Documents\Private\GitHub\MyApp\env\lib\site-packages\django\apps\registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\MyUser001\Documents\Private\GitHub\MyApp\env\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Users\MyUser001\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\MyUser001\Documents\Private\GitHub\MyApp\env\lib\site-packages\social_django\__init__.py", line 4, in <module>
    from social_core.backends.base import BaseAuth
  File "C:\Users\MyUser001\Documents\Private\GitHub\MyApp\env\lib\site-packages\social_core\backends\base.py", line 3, in <module>
    from requests import request, ConnectionError
ImportError: cannot import name 'request'
```

Has anyone seen this issue?

**Comment by kommonSense** [comment]
found solution yet?!
facing same issue!

**Comment by LeNikki** [comment]
Encountered the same problem:  django.shortcuts import render,  request
Until I realized I only need to import: from django.shortcuts import render, redirect
There's no need to import request anymore. Hope this helps.
