### ISSUE TITLE
Facing trouble when using it python 3.6.7 and django 2.x

### ISSUE THREAD

**Issue by Samarpitr** [python-social-auth/social-app-django#206]
(Pdb) [26/May/2019 07:09:26] "GET /complete/google-oauth2/?state=6LB0nuEG7C8vl8l6Cjwnohd3SNsgphmO&code=4/VgETaA0n87m2EfGEDALuDDKR98-BXAOM4GkiyMDTH2eTuRrx4AWCwp6ie-w4bLFNfMWXNQJmlc-ztpm_f5_PXIQ&scope=email+profile+https://www.googleapis.com/auth/userinfo.email+https://www.googleapis.com/auth/userinfo.profile+openid&authuser=0&session_state=dedc8348f8b357816ccc485fe5554c6e5ec00f97..c674&prompt=none HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): accounts.google.com:443
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 400 None
Internal Server Error: /complete/google-oauth2/
Traceback (most recent call last):
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/social_core/utils.py", line 259, in wrapper
    return func(*args, **kwargs)
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/social_core/backends/oauth.py", line 401, in auth_complete
    method=self.ACCESS_TOKEN_METHOD
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/social_core/backends/oauth.py", line 373, in request_access_token
    return self.get_json(*args, **kwargs)
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/social_core/backends/base.py", line 238, in get_json
    return self.request(url, *args, **kwargs).json()
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/social_core/backends/base.py", line 234, in request
    response.raise_for_status()
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://accounts.google.com/o/oauth2/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/social_django/utils.py", line 49, in wrapper
    return func(request, backend, *args, **kwargs)
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/social_django/views.py", line 33, in complete
    *args, **kwargs)
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/social_core/actions.py", line 43, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/social_core/backends/base.py", line 40, in complete
    return self.auth_complete(*args, **kwargs)
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/social_core/utils.py", line 262, in wrapper
    raise AuthCanceled(args[0], response=err.response)
social_core.exceptions.AuthCanceled: Authentication process canceled
ERROR:django.request:Internal Server Error: /complete/google-oauth2/
Traceback (most recent call last):
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/social_core/utils.py", line 259, in wrapper
    return func(*args, **kwargs)
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/social_core/backends/oauth.py", line 401, in auth_complete
    method=self.ACCESS_TOKEN_METHOD
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/social_core/backends/oauth.py", line 373, in request_access_token
    return self.get_json(*args, **kwargs)
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/social_core/backends/base.py", line 238, in get_json
    return self.request(url, *args, **kwargs).json()
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/social_core/backends/base.py", line 234, in request
    response.raise_for_status()
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://accounts.google.com/o/oauth2/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/social_django/utils.py", line 49, in wrapper
    return func(request, backend, *args, **kwargs)
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/social_django/views.py", line 33, in complete
    *args, **kwargs)
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/social_core/actions.py", line 43, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/social_core/backends/base.py", line 40, in complete
    return self.auth_complete(*args, **kwargs)
  File "/home/samarpit/Music/dopshub-backend/env/lib/python3.6/site-packages/social_core/utils.py", line 262, in wrapper
    raise AuthCanceled(args[0], response=err.response)
social_core.exceptions.AuthCanceled: Authentication process canceled

Someone posted out the following for python3 google oauthapis:
https://stackoverflow.com/questions/53771382/requests-exceptions-httperror-400-client-error-bad-request-for-url-https-ac

**Comment by nijel** [comment]
Let's assume this is fixed now as google-oauth2 works just fine.
