### ISSUE TITLE
Issue when migrate version 1.0.0

### ISSUE THREAD

**Issue by camilonova** [python-social-auth/social-app-django#22]
After upgrading I'm getting this error:
```
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/showmigrations.py", line 36, in handle
    return self.show_list(connection, options['app_labels'])
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/showmigrations.py", line 44, in show_list
    loader = MigrationLoader(connection, ignore_no_migrations=True)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/loader.py", line 293, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/loader.py", line 276, in _reraise_missing_dependency
    raise exc
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/loader.py", line 286, in build_graph
    self.graph.add_dependency(migration, key, parent)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/graph.py", line 126, in add_dependency
    parent
django.db.migrations.exceptions.NodeNotFoundError: Migration social_django.0006_partial dependencies reference nonexistent parent node ('social_django', '0005_auto_20160727_2333')
```

**Comment by camilonova** [comment]
I removed all tables manually an removed references at the django_migrations table to start from scratch and I'm getting this:
```
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/showmigrations.py", line 36, in handle
    return self.show_list(connection, options['app_labels'])
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/showmigrations.py", line 44, in show_list
    loader = MigrationLoader(connection, ignore_no_migrations=True)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/loader.py", line 293, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/loader.py", line 276, in _reraise_missing_dependency
    raise exc
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/loader.py", line 286, in build_graph
    self.graph.add_dependency(migration, key, parent)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/graph.py", line 126, in add_dependency
    parent
django.db.migrations.exceptions.NodeNotFoundError: Migration social_django.0005_auto_20160727_2333 dependencies reference nonexistent parent node ('social_django', '0004_auto_20160423_0400')
```

**Comment by camilonova** [comment]
This is related with #16 but here I'm starting from scratch.

**Comment by camilonova** [comment]
I had to run this SQL query:
```
update django_migrations set app='social_django' where app='default';
```
This allowed me to run the migrations without any issue.
