### ISSUE TITLE
 TypeError: pipeline() got multiple values for argument 'pipeline_index'

### ISSUE THREAD

**Issue by craigds** [python-social-auth/social-app-django#222]
```
TypeError: pipeline() got multiple values for argument 'pipeline_index'
  File "tulip/social/views.py", line 77, in complete
    **kwargs
  File "social_core/actions.py", line 39, in do_complete
    user = backend.continue_pipeline(partial)
  File "social_core/backends/base.py", line 201, in continue_pipeline
    **partial.kwargs)
  File "social_django/strategy.py", line 107, in authenticate
    return authenticate(*args, **kwargs)
  File "django/contrib/auth/__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "social_core/backends/base.py", line 80, in authenticate
    return self.pipeline(pipeline, *args, **kwargs)
```

# mock code that reproduces the bug

```python
from django.http import HttpRequest

def continue_pipeline():
    return django_strategy_authenticate(
        "backend", pipeline_index=12
    )


def django_strategy_authenticate(backend, *args, **kwargs):
    kwargs['backend'] = backend
    return django_contrib_auth_authenticate(*args, **kwargs)


def django_contrib_auth_authenticate(request=None, **credentials):
    """
    If the given credentials are valid, return a User object.
    """
    baseauth_authenticate(request, **credentials)


def baseauth_authenticate(*args, **kwargs):
    args, kwargs = clean_authenticate_args(*args, **kwargs)

    return baseauth_pipeline("pipeline", *args, **kwargs)

def clean_authenticate_args(*args, **kwargs):
    """Cleanup request argument if present, which is passed to
    authenticate as for Django 1.11"""
    if len(args) > 0 and isinstance(args[0], HttpRequest):
        kwargs['request'], args = args[0], args[1:]
    return args, kwargs

def baseauth_pipeline(pipeline, pipeline_index=0, *args, **kwargs):
    # we never get here
    print("hey it actually worked")


continue_pipeline()

```

# suspects

* `django.contrib.auth.authenticate` is defaulting the `request` kwarg to `None` because it's not provided by the `DjangoStrategy`.
* This means that `DjangoStrategy.clean_authenticate_args` doesn't remove the request from `args` to put it into `kwargs`.
* which in turn means that `BaseAuth.authenticate` passes the request (`None`) as the second arg to `BaseAuth.pipeline`, which is supposed to be `pipeline_index`
* and since `pipeline_index` is _also_ passed as a keyword arg, this raises a `TypeError`

# versions and lineage

```
Django==2.1.11
social-auth-app-django==3.1.0
social-auth-core==3.2.0
```

moved from python-social-auth/social-core#392 once I figured out where the problem lies.
might be related to: #57, #77.

**Comment by ccsv** [comment]
I think I got the same error running manage.py migrate

```
python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\0\Envs\hmf\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\0\Envs\hmf\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\0\Envs\hmf\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\0\Envs\hmf\lib\site-packages\django\core\management\base.py", line 361, in execute
    self.check()
  File "C:\Users\0\Envs\hmf\lib\site-packages\django\core\management\base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\0\Envs\hmf\lib\site-packages\django\core\management\commands\migrate.py", line 65, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "C:\Users\0\Envs\hmf\lib\site-packages\django\core\management\base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\0\Envs\hmf\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\0\Envs\hmf\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\0\Envs\hmf\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\0\Envs\hmf\lib\site-packages\django\urls\resolvers.py", line 399, in check
    for pattern in self.url_patterns:
  File "C:\Users\0\Envs\hmf\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\0\Envs\hmf\lib\site-packages\django\urls\resolvers.py", line 584, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\0\Envs\hmf\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\0\Envs\hmf\lib\site-packages\django\urls\resolvers.py", line 577, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\0\Envs\hmf\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\0\Desktop\hmf\saleor\saleor\urls.py", line 35, in <module>
    url("", include("social_django.urls", namespace="social")),
  File "C:\Users\0\Envs\hmf\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\0\Envs\hmf\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\0\Envs\hmf\lib\site-packages\social_django\urls.py", line 6, in <module>
    from . import views
  File "C:\Users\0\Envs\hmf\lib\site-packages\social_django\views.py", line 10, in <module>
    from .utils import psa
  File "C:\Users\0\Envs\hmf\lib\site-packages\social_django\utils.py", line 18, in <module>
    Strategy = module_member(STRATEGY)
  File "C:\Users\0\Envs\hmf\lib\site-packages\social_core\utils.py", line 62, in module_member
    module = import_module(mod)
  File "C:\Users\0\Envs\hmf\lib\site-packages\social_core\utils.py", line 56, in import_module
    __import__(name)
  File "C:\Users\0\Envs\hmf\lib\site-packages\social_django\strategy.py", line 14, in <module>
    from social_core.strategy import BaseStrategy, BaseTemplateStrategy
  File "C:\Users\0\Envs\hmf\lib\site-packages\social_core\strategy.py", line 7, in <module>
    from .pipeline import DEFAULT_AUTH_PIPELINE, DEFAULT_DISCONNECT_PIPELINE
ModuleNotFoundError: No module named 'social_core.pipeline'
```

**Comment by craigds** [comment]
that looks like quite a different  error
