### ISSUE TITLE
KeyError: ('social_django', 'usersocialauth') when applying migrate 0002_add_related_name.py

### ISSUE THREAD

**Issue by root365** [python-social-auth/social-app-django#280]
I'm getting the error 
KeyError: ('social_django', 'usersocialauth') when applying migrate 0002_add_related_name.py

**Comment by caarmen** [comment]
I'm getting this too, did anybody solve this?

**Comment by nijel** [comment]
Something went wrong during the migrations, but it's difficult to tell what without more info. How did it happen? Can you post a full exception?

**Comment by ebuildy** [comment]
I can reproduce, netbox 4.4.9, because in my case, I tried first to install netbox 4.6 then install netbox 4.4.9 in the same DB:

I think migration tool should verify the current DB netbox installation version

```
netbox-1  | ⚙️ Applying database migrations
netbox-1  | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox-1  | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox-1  | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox-1  | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox-1  | Operations to perform:
netbox-1  |   Apply all migrations: account, auth, circuits, contenttypes, core, dcim, django_rq, extras, ipam, netbox_branching, sessions, social_django, taggit, tenancy, thumbnail, users, virtualization, vpn, wireless
netbox-1  | Traceback (most recent call last):
netbox-1  |   File "/opt/netbox/netbox/./manage.py", line 10, in <module>
netbox-1  |     execute_from_command_line(sys.argv)
netbox-1  |   File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
netbox-1  |     utility.execute()
netbox-1  |   File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
netbox-1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
netbox-1  |   File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/base.py", line 416, in run_from_argv
netbox-1  |     self.execute(*args, **cmd_options)
netbox-1  |   File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/base.py", line 460, in execute
netbox-1  |     output = self.handle(*args, **options)
netbox-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-1  |   File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/base.py", line 107, in wrapper
netbox-1  |     res = handle_func(*args, **kwargs)
netbox-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-1  |   File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/commands/migrate.py", line 298, in handle
netbox-1  |     pre_migrate_state = executor._create_project_state(with_applied_migrations=True)
netbox-1  |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-1  |   File "/opt/netbox/venv/lib/python3.12/site-packages/django/db/migrations/executor.py", line 91, in _create_project_state
netbox-1  |     migration.mutate_state(state, preserve=False)
netbox-1  |   File "/opt/netbox/venv/lib/python3.12/site-packages/django/db/migrations/migration.py", line 91, in mutate_state
netbox-1  |     operation.state_forwards(self.app_label, new_state)
netbox-1  |   File "/opt/netbox/venv/lib/python3.12/site-packages/django/db/migrations/operations/fields.py", line 95, in state_forwards
netbox-1  |     state.add_field(
netbox-1  |   File "/opt/netbox/venv/lib/python3.12/site-packages/django/db/migrations/state.py", line 261, in add_field
netbox-1  |     self.models[model_key].fields[name] = field
netbox-1  |     ~~~~~~~~~~~^^^^^^^^^^^
netbox-1  | KeyError: ('social_django', 'code')
```
