### ISSUE TITLE
Cannot login with Facebook or Google (social_core.exceptions.AuthCanceled)

### ISSUE THREAD

**Issue by kj-lai** [python-social-auth/social-app-django#356]
Hi devs,

Versions:
python 3.7
social-auth-app-django 5.0.0

Steps:
1. Open the social:begin url for both Facebook/Google
2. Click my continue (FB) / email (Google)
3. Then it returns the error page.

I have encountered this error. I can't find the reason for this error.
Any suggestions on what went wrong? Thanks.

```
social_core.exceptions.AuthCanceled
social_core.exceptions.AuthCanceled: Authentication process canceled
```

## My settings
```
INSTALLED_APPS = [
    ....,
    'social_django',
    'django_extensions',
]

MIDDLEWARE = [
    ....,
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

AUTHENTICATION_BACKENDS = [
    ....,
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.google.GoogleOAuth2',
]

SOCIAL_AUTH_FACEBOOK_KEY = os.environ.get('FB_KEY')
SOCAIL_AUTH_FACEBOOK_SECRET = os.environ.get('FB_SECRET')

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.environ.get('GG_KEY')
SOCAIL_AUTH_GOOGLE_OAUTH2_SECRET = os.environ.get('GG_SECRET')

SOCIAL_AUTH_LOGIN_REDIRECT_URL = 'index'
SOCIAL_AUTH_RAISE_EXCEPTIONS = False
```

## Traceback
```
Development server is running at https://[127.0.0.1]:8000/
Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
Quit the server with CTRL-BREAK.
 * Debugger is active!
 * Debugger PIN: 474-097-301
 * Running on https://127.0.0.1:8000/ (Press CTRL+C to quit)
127.0.0.1 - - [10/Oct/2021 13:23:21] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [10/Oct/2021 13:23:22] "GET /user/login/ HTTP/1.1" 200 -
127.0.0.1 - - [10/Oct/2021 13:23:25] "GET /social-auth/login/google-oauth2/ HTTP/1.1" 302 -
127.0.0.1 - - [10/Oct/2021 13:23:31] "GET /social-auth/complete/google-oauth2/?state=NOYaqPye9NaEEeqjzo1nx0FABxHLTe2O&code=4%2F0AX4XfWgxLfHRe-IvD7r2LyvM3_RGzG1VTKimuXEhMF5C20c9F6vw0FggfkbY0Sx4KyDmZQ&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&authuser=0&prompt=consent HTTP/1.1" 500 -
Traceback (most recent call last):
  File "D:\Anaconda3\envs\django\lib\site-packages\social_core\utils.py", line 248, in wrapper
    return func(*args, **kwargs)
  File "D:\Anaconda3\envs\django\lib\site-packages\social_core\backends\oauth.py", line 388, in auth_complete
    method=self.ACCESS_TOKEN_METHOD
  File "D:\Anaconda3\envs\django\lib\site-packages\social_core\backends\oauth.py", line 360, in request_access_token
    return self.get_json(*args, **kwargs)
  File "D:\Anaconda3\envs\django\lib\site-packages\social_core\backends\base.py", line 242, in get_json
    return self.request(url, *args, **kwargs).json()
  File "D:\Anaconda3\envs\django\lib\site-packages\social_core\backends\base.py", line 238, in request
    response.raise_for_status()
  File "C:\Users\KJ\AppData\Roaming\Python\Python37\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://accounts.google.com/o/oauth2/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\django\lib\site-packages\django\contrib\staticfiles\handlers.py", line 76, in __call__
    return self.application(environ, start_response)
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\base.py", line 130, in get_response
    response = self._middleware_chain(request)
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\exception.py", line 49, in inner
    response = response_for_exception(request, exc)
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\exception.py", line 114, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\exception.py", line 149, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "D:\Anaconda3\envs\django\lib\site-packages\django_extensions\management\technical_response.py", line 40, in null_technical_500_response
    raise exc_value.with_traceback(tb)
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Anaconda3\envs\django\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Anaconda3\envs\django\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Anaconda3\envs\django\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Anaconda3\envs\django\lib\site-packages\social_django\utils.py", line 46, in wrapper
    return func(request, backend, *args, **kwargs)
  File "D:\Anaconda3\envs\django\lib\site-packages\social_django\views.py", line 33, in complete
    *args, **kwargs)
  File "D:\Anaconda3\envs\django\lib\site-packages\social_core\actions.py", line 45, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File "D:\Anaconda3\envs\django\lib\site-packages\social_core\backends\base.py", line 40, in complete
    return self.auth_complete(*args, **kwargs)
  File "D:\Anaconda3\envs\django\lib\site-packages\social_core\utils.py", line 251, in wrapper
    raise AuthCanceled(args[0], response=err.response)
social_core.exceptions.AuthCanceled: Authentication process canceled
127.0.0.1 - - [10/Oct/2021 13:23:31] "GET /social-auth/complete/google-oauth2/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [10/Oct/2021 13:23:31] "GET /social-auth/complete/google-oauth2/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [10/Oct/2021 13:23:31] "GET /social-auth/complete/google-oauth2/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [10/Oct/2021 13:23:31] "GET /social-auth/complete/google-oauth2/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [10/Oct/2021 13:23:31] "GET /social-auth/complete/google-oauth2/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
```

**Comment by melikyan-a** [comment]
@kj-lai the problem solved or no?
