### ISSUE TITLE
Cannot oauth to Twitter

### ISSUE THREAD

**Issue by l1z4a** [python-social-auth/social-app-django#360]
### Expected behaviour

A user should be able to complete the 3-legged oauth flow and a new user account should have been created when signing up via Twitter.

### Actual behaviour

I see this error at `/api/oauth/complete/twitter/`:
403 Client Error: Forbidden for url: https://api.twitter.com/1.1/account/verify_credentials.json?include_email=true

### What are the steps to reproduce this issue?

Input clear steps to reproduce the issue for a maintainer.

1. Set up a Twitter App. Go to https://developer.twitter.com and sign up for a Twitter developer account. Create an app. Select "Read and Write" (Read + Post Tweets and profile information) under App Permissions. Under "Authentication settings" enable "3-legged OAuth". Under callback URLs add `http://localhost:8000/api/oauth/complete/twitter/`. Enable "Request email address from users".
2. Following the documentation here: https://python-social-auth.readthedocs.io/en/latest/configuration/django.html install `social-auth-app-django`: ``` pip install social-auth-app-django ```
3. Add `'social_django'` to your `INSTALLED_APPS` in `settings.py`
4. Add the following lines to `settings.py`:
```
SOCIAL_AUTH_JSONFIELD_ENABLED = True
SOCIAL_AUTH_URL_NAMESPACE = "social"

SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.social_user",
    "social_core.pipeline.user.get_username",
    "social_core.pipeline.social_auth.associate_by_email",
    "social_core.pipeline.user.create_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    "social_core.pipeline.user.user_details",
    "social_core.pipeline.user.associate_by_email",
)

SOCIAL_AUTH_TWITTER_KEY = os.environ.get("APP_OAUTH_TWITTER_API_KEY")
SOCIAL_AUTH_TWITTER_SECRET = os.environ.get(
    "APP_OAUTH_TWITTER_API_KEY_SECRET"
)

LOGIN_REDIRECT_URL = "/"

AUTHENTICATION_BACKENDS = (
    "social_core.backends.twitter.TwitterOAuth",
    "django.contrib.auth.backends.ModelBackend",
)

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"
```
5. Run migrations and start development server:
```
python manage.py migrate  --no-input
python manage.py runserver 0.0.0.0:8000
```

### Any logs, error output, etc?

```
Environment:

Request Method: GET
Request URL: http://localhost:8000/api/oauth/complete/twitter/?redirect_state=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&oauth_token=XXXXXXXXXXXXXXX-XXXXXXXXXXXX&oauth_verifier=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Django Version: 3.2.9
Python Version: 3.9.7

Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'social_django']

Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/social_django/utils.py", line 49, in wrapper
    return func(request, backend, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/social_django/views.py", line 31, in complete
    return do_complete(request.backend, _do_login, user=request.user,
  File "/usr/local/lib/python3.9/site-packages/social_core/actions.py", line 45, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/social_core/backends/base.py", line 40, in complete
    return self.auth_complete(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/social_core/utils.py", line 248, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/social_core/backends/oauth.py", line 181, in auth_complete
    return self.do_auth(access_token, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/social_core/utils.py", line 248, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/social_core/backends/oauth.py", line 188, in do_auth
    data = self.user_data(access_token)
  File "/usr/local/lib/python3.9/site-packages/social_core/backends/twitter.py", line 37, in user_data
    return self.get_json(
  File "/usr/local/lib/python3.9/site-packages/social_core/backends/base.py", line 242, in get_json
    return self.request(url, *args, **kwargs).json()
  File "/usr/local/lib/python3.9/site-packages/social_core/backends/base.py", line 238, in request
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

Exception Type: HTTPError at /api/oauth/complete/twitter/
Exception Value: 403 Client Error: Forbidden for url: https://api.twitter.com/1.1/account/verify_credentials.json?include_email=true
```

### Any other comments?

* Documentation for `/account/verify_credentials.json` can be found here: https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/manage-account-settings/api-reference/get-account-verify_credentials

**Comment by l1z4a** [comment]
For others that are having this same issue, in my case I was able to check the body of the response from `/account/verify_credentials.json`:

```
{'errors': [{'message': 'You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve', 'code': 453}]}
```

**Comment by wtl1997** [comment]
hi,I had the same problem. How did you solve it
