### ISSUE TITLE
clean_authenticate_args() got multiple values for keyword argument 'request'

### ISSUE THREAD

**Issue by chadsaun** [python-social-auth/social-app-django#77]
In `social_core/backends/base.py` on line 79 I'm getting this error `clean_authenticate_args() got multiple values for keyword argument 'request'`. 

Here is line 79:
```
args, kwargs = self.strategy.clean_authenticate_args(*args, **kwargs)
```

And here is the signature for DjangoStrategy clean_authentication_args:
```
def clean_authenticate_args(self, request=None, *args, **kwargs):
```

**Comment by huypxgear** [comment]
I have the same issue. I use Django v2.0 python 3.6
```
Traceback (most recent call last):
  File "/opt/kff/Whiplash-Server-Env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/opt/kff/Whiplash-Server-Env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/kff/Whiplash-Server-Env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/kff/Whiplash-Server-Env/lib/python3.6/site-packages/ddtrace/contrib/django/patch.py", line 80, in wrapper
    return func(mod, pin, wrapped, instance, args, kwargs)
  File "/opt/kff/Whiplash-Server-Env/lib/python3.6/site-packages/ddtrace/contrib/django/patch.py", line 252, in wrapped
    return func(*args, **kwargs)
  File "/opt/kff/Whiplash-Server-Env/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/kff/Whiplash-Server-Env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/kff/Whiplash-Server-Env/lib/python3.6/site-packages/social_django/utils.py", line 46, in wrapper
    return func(request, backend, *args, **kwargs)
  File "/opt/kff/Whiplash-Server-Env/lib/python3.6/site-packages/social_django/views.py", line 33, in complete
    *args, **kwargs)
  File "/opt/kff/Whiplash-Server-Env/lib/python3.6/site-packages/social_core/actions.py", line 45, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File "/opt/kff/Whiplash-Server-Env/lib/python3.6/site-packages/social_core/backends/base.py", line 40, in complete
    return self.auth_complete(*args, **kwargs)
  File "/opt/kff/Whiplash-Server-Env/lib/python3.6/site-packages/social_core/utils.py", line 247, in wrapper
    return func(*args, **kwargs)
  File "/opt/kff/Whiplash-Server-Env/lib/python3.6/site-packages/social_core/backends/oauth.py", line 402, in auth_complete
    *args, **kwargs)
  File "/opt/kff/Whiplash-Server-Env/lib/python3.6/site-packages/social_core/utils.py", line 247, in wrapper
    return func(*args, **kwargs)
  File "/opt/kff/Whiplash-Server-Env/lib/python3.6/site-packages/social_core/backends/oauth.py", line 413, in do_auth
    return self.strategy.authenticate(*args, **kwargs)
  File "/opt/kff/Whiplash-Server-Env/lib/python3.6/site-packages/social_django/strategy.py", line 105, in authenticate
    return authenticate(*args, **kwargs)
  File "/opt/kff/Whiplash-Server-Env/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 70, in authenticate
    user = _authenticate_with_backend(backend, backend_path, request, credentials)
  File "/opt/kff/Whiplash-Server-Env/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 115, in _authenticate_with_backend
    return backend.authenticate(*args, **credentials)
  File "/opt/kff/Whiplash-Server-Env/lib/python3.6/site-packages/social_core/backends/base.py", line 79, in authenticate
    args, kwargs = self.strategy.clean_authenticate_args(*args, **kwargs)
TypeError: clean_authenticate_args() got multiple values for argument 'request'
```

**Comment by nijel** [comment]
Should be fixed since https://github.com/python-social-auth/social-app-django/commit/88420fa6cc8d1000e031505f29e1277b583421f7
